server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: space
          uri: http://localhost:8082
          predicates:
            - Path=/spaces/**, 
        - id: reserve
          uri: http://localhost:8083
          predicates:
            - Path=/facilities/**,
        - id: center
          uri: http://localhost:8084
          predicates:
            - Path=, /myPages/**
        - id: analysis
          uri: http://localhost:8085
          predicates:
            - Path=/analyses/**, /facilityUtilizationRates/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: space
          uri: http://space:8080
          predicates:
            - Path=/spaces/**, 
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/facilities/**, 
        - id: center
          uri: http://center:8080
          predicates:
            - Path=, 
        - id: analysis
          uri: http://analysis:8080
          predicates:
            - Path=/analyses/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
